### ISSUE TITLE
Failure when doing composer update

### ISSUE THREAD

**Issue by CGavrila** [rbewley4/laravel-couchdb#3]
It seems that composer update encounters a problem when trying to get `rbewley4/laravel-couchdb`. More specifically, it seems that it can't get `doctrine/couchdb`.

I have forked this repository on my own account and changed composer.json from `"doctrine/couchdb": "dev"` to `"doctrine/couchdb": "dev-master"` like this: [composer.json](https://github.com/CGavrila/laravel-couchdb/blob/master/composer.json). I then replaced `rbewley4/laravel-couchdb` with `CGavrila/laravel-couchdb` in my project's composer.json file and it just worked.

I don't know enough about composer to say exactly what is causing the issue and why this was working fine a couple of weeks ago, and now doesn't. I just guess it doesn't point to the right branch of doctrine/couchdb.

 I also haven't tried it in a separate project in order to replicate it.

**Comment by CGavrila** [comment]
Oops, should have checked the pull requests section before posting this. It looks like there is one for this exact issue: pull request #2.

I'll just leave the issue open for visibility until this is dealt with.

**Comment by rbewley4** [comment]
Try it now. I just merged pull request #2.

**Comment by CGavrila** [comment]
Thanks, @rbewley4, It is working now!

Closing.
